# Generated by Django 3.2 on 2021-05-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20210523_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='note',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
