# Generated by Django 3.2.3 on 2021-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_status_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='is_alive',
        ),
    ]
