# Generated by Django 3.2.3 on 2021-05-31 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_alive_previous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitor'),
        ),
    ]
